version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: g360-backend
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
      - ./node_modules:/app/node_modules
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: g360-frontend
    ports:
      - "3002:3000"
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages:/app/packages
      - ./node_modules:/app/node_modules
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - backend   
    environment:
      NODE_ENV: development

  # mobile:
  #   build:
  #     context: .
  #     dockerfile: apps/mobile/Dockerfile
  #   container_name: g360-mobile
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./apps/mobile:/app/apps/mobile
  #     - ./packages:/app/packages
  #     - ./node_modules:/app/node_modules
  #   depends_on:
  #     - backend
  #   environment:
  #     NODE_ENV: development